import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Cursor } from "./components/cursor";
import { ThemeProvider } from "./components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/bwo5nqc.css" />
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Cursor />
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
